version: "3.3"
services:
    messageq:
        container_name: "messageq"
        image: rabbitmq:3.8-management-alpine
        environment:
            # adding plain text, but we need to set auth while deploying into remote
            - RABBITMQ_DEFAULT_USER=sunil
            - RABBITMQ_DEFAULT_PASS=admin
        ports:
            - '7086:5672' # for amqp
            - '7087:15672' # to access over HTTP
        logging:
            driver: none
    app:
        build:
            context: ./
        ports:
            - "7085:7085"
        volumes:
            - ./:/pizza-pipeline/
        depends_on:
            - messageq
